[theme]
primaryColor = "#3b82f6"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#1e3a8a"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
